### ISSUE TITLE
[1.12.2] Slight visual issue when using mod with Galacticraft.

### ISSUE THREAD

**Issue by RavenChan1023** [DonBruce64/RealFirstPersonRender#10]
There's a weird issue when using the mod with Galacticraft where the oxygen helmet disappears and reappears on screen depending on where I look. If I look down, it's visible but if I look up, it's not. I was hoping you could add a layer of compatibility by adding a slight overlay, and if you can't, that's fine.

![2018-11-03_09 50 53](https://user-images.githubusercontent.com/37986598/47953690-08550480-df4f-11e8-804e-b0b20c68afa9.png)

**Comment by DonBruce64** [comment]
Inter-mod compatibility isn't really something I can focus on with RFPR as that would cause it to break whenever mod authors update their mods.  See Issue #6 for a similar case with Baubles.
