### ISSUE TITLE
Disable Rendering On Horse?

### ISSUE THREAD

**Issue by mmmilord** [DonBruce64/RealFirstPersonRender#11]
Not gonna ask you to fix anything since I can live with the limitations of the mod, but is there a way I can disable rendering when on horse-back, like how the S:OverrideItems option works? since whenever I jump with the horse it starts clipping through my char and spazzing out. I could just use f1, but i'm having to press it every time I mount/dismount so having it do it automatically would be great. Works fine other than that one instance, thanks in advance.

**Comment by DonBruce64** [comment]
Closing as invalid due to lack of response by user and inability to replicate.
