### ISSUE TITLE
Arms Reset when pressing F5

### ISSUE THREAD

**Issue by Elspar2** [DonBruce64/RealFirstPersonRender#15]
When I press F5 in-game it goes into third person, then rear view like expected. But upon returning to first-person, my arms are displaying like in default minecraft, while my body is still rendered normally.

**Comment by DonBruce64** [comment]
So what you are saying, is that when you go into first-person a second time RFPR isn't hiding your arms like it should be?

**Comment by Elspar2** [comment]
Yes. It doesn't happen every time, but randomly. Once it does happen, it never corrects itself.

**Comment by DonBruce64** [comment]
Odd.  Do you have any other mods installed besides RFPR?

**Comment by DonBruce64** [comment]
Closing due to lack of response by user.
