### ISSUE TITLE
1.13?

### ISSUE THREAD

**Issue by DJJub47** [DonBruce64/RealFirstPersonRender#17]
When will RFPR be updated to MC 1.13? If it won't be, then I'm gonna have to learn the Forge 1.13 SDK.

**Comment by DonBruce64** [comment]
I don't plan on ever updating it to 1.13.  In fact, I don't know if I'll ever mod for 1.13.  Forge's constant changing of things for updates has bit me since I've modded in 1.7.10, and 1.13 is by and far the worst offender.  Will likely switch to other projects as 1.12.2 becomes obsolete.

**Comment by DJJub47** [comment]
I understand. Thank you.

**Comment by Redd56** [comment]
Mods updating to 1.13. is good joke
