### ISSUE TITLE
More player models and mo bends..

### ISSUE THREAD

**Issue by elainyx06** [DonBruce64/RealFirstPersonRender#19]
I cant sit, crawl, or lay down with more player models because of mo bends. I try putting extra parts with more player models and it still wouldn't show up. i'm using version 1.12.2

**Comment by DonBruce64** [comment]
Which version of RFPR are you using?

**Comment by elainyx06** [comment]
wait what does rfpr abrreviate? I might have the wrong version and I dont even know

**Comment by DonBruce64** [comment]
Uuuh, the name of the GitHub you posted this issue to?  RealFirstPersonRender

**Comment by elainyx06** [comment]
wait i didn't mean to put it under that. I meant to put that just by itself
i have the current mo bends and current 1.12.2 more player models. the issue is i can't punch with both fists. I also tried putting bunny ears from mpm with my character and it didnt show. i tried adjusting height and it didn't change and it was shaky when i flew or ran,

**Comment by DonBruce64** [comment]
Again, what is the version you are using?  Got a link?  Actual numbers?  Cause I suspect you're not using this mod, and using another mod.

**Comment by elainyx06** [comment]
1.12.2 i checked

**Comment by DonBruce64** [comment]
You aren't listening.  I don't care which *Minecraft* version you are using.  I need which *mod* version you are using.  ALL versions of this mod that were current that I worked on were for 1.12.2, as is the replacement mod that I suspect you have issues with.  If you don't want to give me a link or list the full version, I can't help.

**Comment by elainyx06** [comment]
https://www.curseforge.com/minecraft/mc-mods/first-person-render/files/2562435 is  for RFPR. and for More player model https://www.curseforge.com/minecraft/mc-mods/more-player-models/files/2837187. and the mod version for mo bends is https://www.curseforge.com/minecraft/mc-mods/mo-bends/files/2984182. Its not that I didn't want to I was just busy doing something important and didnt read the full thing. sorry.

**Comment by DonBruce64** [comment]
Okay, now I'm confused.  That RFPR you said you downloaded hasn't been in-use since 2018...  That's the old version of the mod.

**Comment by elainyx06** [comment]
I didnt know so big oof. So which is the one I use now?

**Comment by DonBruce64** [comment]
Are you sure that's the same mod you downloaded?  If so, you need to use this one:
https://www.curseforge.com/minecraft/mc-mods/real-first-person-render

That's the updated codebase that I worked on.  Though rejah took that over about a year ago.  How the heck did you get to this GitHub anyways?  Cause it's not linked on either the old mod's Curse page, or the new one.  Do I still have a link flying around somewhere?

**Comment by elainyx06** [comment]
Yeah I found it just clicking on random things, Its was in someones comments on curse forge

**Comment by elainyx06** [comment]
thanks for the help

**Comment by elainyx06** [comment]
im gonna see if it works

**Comment by DonBruce64** [comment]
Closing due to lack of response by user.
