### ISSUE TITLE
Epicfight and realfirstperson2

### ISSUE THREAD

**Issue by ainlzj** [DonBruce64/RealFirstPersonRender#20]
Epicfight is not compatible with realfirstperson2 
[![TR4CJHA2 B69EX S%}(Z~VA](https://user-images.githubusercontent.com/66135518/94327194-e8fc7000-ffdb-11ea-85da-200a70a435e7.png)
](url)

**Comment by DonBruce64** [comment]
I keep forgetting to close this GitHub.  This is for the original RFPR, not RFPR2 one maintained by the new guy.

**Comment by ainlzj** [comment]
Where can I ask the question
