### ISSUE TITLE
2 bugs in mc 1.12.2.

### ISSUE THREAD

**Issue by flyingcatt3** [DonBruce64/RealFirstPersonRender#4]
1.In the first person perspective,when swimming, I can’t see my head.  (I installed mobends so I'm able to swim in 1.12.2)
2.When press F1, the function of this mod is good or bad.
[https://drive.google.com/open?id=1B9qrTjytaxSY5K3gRneJiyLJ4_-idQmY](url)

**Comment by DonBruce64** [comment]
RFPR never renders the player's head as it causes the camera to be obstructed by it during normal operation.  Mo-bends modifies the rotation of the player model about the player's position point, which is the player's feet, not the player's camera point, which is the head, so it makes sense that you are seeing a body without a head.  Nothing I can do about that.
