### ISSUE TITLE
Bow Not Animating

### ISSUE THREAD

**Issue by CzarNick14** [DonBruce64/RealFirstPersonRender#5]
Whenever I draw a bow it will stay pointing at the floor rather than actually aiming. The arrow still shoot normally, but this is rather annoying. Playing in 1.12.2

**Comment by DonBruce64** [comment]
I cannot duplicate this on my end.  Whenever I aim a bow my player model moves his hands upwards, both in normal third-person mode and in RFPR first-person mode.  Closing this as it is working perfectly and as designed.  The player model's rotation is based on the MC rendering code, so if the model isn't rotating in first-person some mod or something must be inhibiting it and it is not something RFPR can override.
![2018-07-24_19 08 02](https://user-images.githubusercontent.com/15241611/43172618-ba4c8e3a-8f75-11e8-8a67-f720a2e0e565.png)
![2018-07-24_19 08 14](https://user-images.githubusercontent.com/15241611/43172619-ba5e1218-8f75-11e8-895f-7943b8b03f8b.png)

**Comment by CzarNick14** [comment]
Thanks for the reply. You're a great mod author by the way. Keep it up!
I'll try to figure out the problem on my end.
