### ISSUE TITLE
Sometimes the model stops rendering.

### ISSUE THREAD

**Issue by alpharou** [DonBruce64/RealFirstPersonRender#7]
When the player dies far away from the spawn point, teleports to another location, the model gets seemingly lost and wont render until you quit to the main menu and load the world again.

It seems to happen more frequently when minecraft is under heavy load, but I've also tested it without any other mods and it still happens. For example, go "/tp ~ ~ ~10000" and you've made yourself invisible. No amount of f1 will refresh whatever is breaking.

**Comment by DonBruce64** [comment]
Fixed as of V9.0.0.  If the player would teleport (either through TP or death like you said), and if the chunk they were in prior didn't update, the model would get stuck there.  Added a check to ensure the model didn't get stuck in an unloaded chunk, so now if you get out of update range RFPR will wait 1 second and if it doesn't hear back from the model it will assume it's stuck and will re-render it.  Tested both with /TP and /KILL commands, and a trip to the Nether.  All appears to be working.
